server:
  port: 8080

spring:
  application:
    name: todo-port-test

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/app_db}
    username: ${SPRING_DATASOURCE_USERNAME:app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:app_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
